package Daje::Workflow::GeneratePerl::Base::Common;
use Mojo::Base -base, -signatures;

# NAME
# ====
#
# Daje::Workflow::GeneratePerl::Activity - It creates perl code
#
#
# DESCRIPTION
# ===========
#
# pod generated by Pod::Autopod - keep this line to make pod updates possible ####################
#
#
# REQUIRES
# ========
#
#
#
#
#
# METHODS
# =======
#


has 'templates' ;
has 'json' ;


1;

#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################



