package Daje::Workflow::GeneratePerl::Base::Common;
use Mojo::Base -base, -signatures;

# NAME
# ====
#
# Daje::Workflow::GeneratePerl::Base::Common - Base class
#
#
# DESCRIPTION
# ===========
#
# Simple base class
#
#
# REQUIRES
# ========
#
#   use Mojo::Base
#
#
#
# METHODS
# =======
#
#   has 'templates' ;
#   has 'json' ;
#


has 'templates' ;
has 'json' ;


1;

#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################



